name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOSTNAME }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          envs: SHA
          script_stop: true
          script: |
            cd parkhang
            git pull origin master
            docker-compose -f production.yml up --build -d django
            docker system prune -af
            
